language: python
python: 3.6.4

install:
  - pip install -r requirements
  - pip install coveralls

script:
  - python -m pytest --cov-report term-missing --cov=resources

after_success:
  - coveralls

notifications:
  - email: false

