"""empty message

Revision ID: 5f4641a90cd0
Revises: 
Create Date: 2018-05-25 11:22:05.910863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4641a90cd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=80), nullable=False),
    sa.Column('book_author', sa.String(length=50), nullable=False),
    sa.Column('book_copies', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('book_author'),
    sa.UniqueConstraint('book_title')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
